Update node.js.yml

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -12,7 +12,7 @@ jobs:
 
     strategy:
       matrix:
-        node-version: [ '20.x' ]
+        node-version: [ 'latest' ]
 
     steps:
       - uses: actions/checkout@v4
@@ -29,8 +29,12 @@ jobs:
       - name: Build project
         run: npm run build --if-present
 
-      - name: Run tests
-        run: npm test
+      - name: Verify build output
+        run: |
+          if [ ! -d "dist" ]; then
+            echo "Build failed: dist folder not found!"
+            exit 1
+          fi
 
       - name: Login to DockerHub
         uses: docker/login-action@v3
